spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ncbt
    username: root
    password: '0000'
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: { client-id }
            client-secret: { client-secret }
            redirect-uri: "http://localhost:8080/"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

mybatis:
  type-aliases-package: kr.kh.backend
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 6b9e99461f38d94afabeec2b65fc44a8baa27b6e11c8409e2b0f0cb2b7d5c3d1

